# Generated by Django 3.0.5 on 2020-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='book',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
